# Generated by Django 4.1.2 on 2022-10-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionNum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecat', models.CharField(max_length=50, unique=True, verbose_name='nombre categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepro', models.CharField(max_length=50)),
                ('descripcionpro', models.CharField(max_length=255, verbose_name='descripcion del producto')),
                ('imagenpro', models.ImageField(blank=True, default='default_conejo.jpg', null=True, upload_to='')),
                ('stock', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionNum.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
